### ISSUE TITLE
Node 8.9 的 Docker 中全局安装 ruo-cli 失败 

### ISSUE THREAD

**Issue by ckaqq** [ruojs/ruo-cli#1]
![image](https://user-images.githubusercontent.com/11495438/33814486-6ba83944-de65-11e7-9f26-ce22090fedb5.png)

**Comment by sabakugaara** [comment]
root 用户安装的时候，加上 `--unsafe-perm`，否则在执行安装脚本时，为非 root 用户，导致创建软连失败
